### ISSUE TITLE
__get_validated_git_repos__ 오류 처리

### ISSUE THREAD

**Issue by ghost** [kookmin-sw/2018-cap1-6#25]
clone한 repo 잘 가리키게 하기(람다의 tmp 폴더에 있는)
/tmp/zesow/webhooktest2/branch/master

**Comment by ghost** [comment]
[Errno 2] No such file or directory: OSError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 201, in lambda_handler
jsonfile = run_gitInspector(repo_path, repo_name)
File "/var/task/lambda_function.py", line 126, in run_gitInspector
gitinspector.main()
File "/var/task/gitinspector/gitinspector.py", line 153, in main
repos = __get_validated_git_repos__(url)
File "/var/task/gitinspector/gitinspector.py", line 129, in __get_validated_git_repos__
cloned_repo.location = basedir.get_basedir_git(cloned_repo.location)
File "/var/task/gitinspector/basedir.py", line 38, in get_basedir_git
stdout=subprocess.PIPE, stderr=open(os.devnull, "w"))
File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

lambda상에서 subprocess로 처리하는 과정에서 문제 발생

**Comment by ghost** [comment]
lambda 에 git이 안 깔려 있기 때문에 그런 것 같다.

**Comment by ghost** [comment]
subprocess.call() 을 이용하여 yum으로 git을 설치해 봤으나,
`Could not set cachedir: [Errno 30] Read-only file system: '/var/tmp/yum-sbx_user1059-D0R6xl'`
오류가 뜨며 접근이 불가능하다고 한다.

**Comment by ghost** [comment]
~~https://github.com/lambci/docker-lambda
람다에 사용 가능한 docker가 있다고 한다.
여기서 git이 설치된 환경을 구축해서 람다에 올리면 되지 않을까?~~
-> 알고보니 로컬에서 lambda 테스트 환경을 구축해주는 docker image 같음..

**Comment by ghost** [comment]
혹은 gitinspector에서 subprocess로 git 호출하는 부분을 전부 pygit2라이브러리를 쓰도록 수정할 수도 있는데, pygit2에 기능들이 다 있을지 모르겠다.

**Comment by ghost** [comment]
https://hackernoon.com/how-did-i-hack-aws-lambda-to-run-docker-containers-7184dc47c09b
실제로 해본 사람의 포스팅을 찾았다.

**Comment by ghost** [comment]
4시간마다 재설치 해야 한다고 해서 포기하기로 결정.
